import Footer from "@/widgets/footer/ui/Footer";
import { Header } from "@/widgets/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="main-container">
      <Header />
      {children}
      <Footer />
    </div>
  );
}
