// Generated by ts-to-zod
import {
  adminActivityLogValuesSchema,
  adminPermissionsSchema,
  orderItemOptionDetailsSchema,
  paymentDetailsSchema,
  productOptionCombinationsSchema,
  productDimensionsSchema,
  searchFiltersSchema
} from "./database-json.schemas";
import { z } from "zod";
export const hkAdminActivityLogsRowSchema = z.object({
  action: z.string(),
  admin_id: z.string(),
  created_at: z.string().nullable(),
  id: z.string(),
  ip_address: z.unknown(),
  new_values: adminActivityLogValuesSchema.nullable(),
  old_values: adminActivityLogValuesSchema.nullable(),
  target_id: z.string().nullable(),
  target_table: z.string(),
  user_agent: z.string().nullable(),
});

export const hkAdminActivityLogsInsertSchema = z.object({
  action: z.string(),
  admin_id: z.string(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ip_address: z.unknown().optional(),
  new_values: adminActivityLogValuesSchema.optional().nullable(),
  old_values: adminActivityLogValuesSchema.optional().nullable(),
  target_id: z.string().optional().nullable(),
  target_table: z.string(),
  user_agent: z.string().optional().nullable(),
});

export const hkAdminActivityLogsUpdateSchema = z.object({
  action: z.string().optional(),
  admin_id: z.string().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ip_address: z.unknown().optional(),
  new_values: adminActivityLogValuesSchema.optional().nullable(),
  old_values: adminActivityLogValuesSchema.optional().nullable(),
  target_id: z.string().optional().nullable(),
  target_table: z.string().optional(),
  user_agent: z.string().optional().nullable(),
});

export const hkAdminActivityLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_admin_activity_logs_admin_id_fkey"),
    columns: z.tuple([z.literal("admin_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkAdminUsersRowSchema = z.object({
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  permissions: adminPermissionsSchema.nullable(),
  role: z.string(),
  user_id: z.string(),
});

export const hkAdminUsersInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  permissions: adminPermissionsSchema.optional().nullable(),
  role: z.string().optional(),
  user_id: z.string(),
});

export const hkAdminUsersUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  permissions: adminPermissionsSchema.optional().nullable(),
  role: z.string().optional(),
  user_id: z.string().optional(),
});

export const hkAdminUsersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_admin_users_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_admin_users_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkBrandsRowSchema = z.object({
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  logo_url: z.string().nullable(),
  name: z.string(),
  slug: z.string(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
  website_url: z.string().nullable(),
});

export const hkBrandsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  name: z.string(),
  slug: z.string(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  website_url: z.string().optional().nullable(),
});

export const hkBrandsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  logo_url: z.string().optional().nullable(),
  name: z.string().optional(),
  slug: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  website_url: z.string().optional().nullable(),
});

export const hkBrandsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_brands_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_brands_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkCartItemsRowSchema = z.object({
  added_price: z.number(),
  created_at: z.string().nullable(),
  id: z.string(),
  product_id: z.string(),
  quantity: z.number(),
  session_id: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable(),
  variant_id: z.string().nullable(),
});

export const hkCartItemsInsertSchema = z.object({
  added_price: z.number(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  product_id: z.string(),
  quantity: z.number(),
  session_id: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  variant_id: z.string().optional().nullable(),
});

export const hkCartItemsUpdateSchema = z.object({
  added_price: z.number().optional(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  product_id: z.string().optional(),
  quantity: z.number().optional(),
  session_id: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  variant_id: z.string().optional().nullable(),
});

export const hkCartItemsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_cart_items_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_cart_items_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_cart_items_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_cart_items_variant_id_fkey"),
    columns: z.tuple([z.literal("variant_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_product_variants"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkCategoriesRowSchema = z.object({
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  image_url: z.string().nullable(),
  is_active: z.boolean().nullable(),
  meta_description: z.string().nullable(),
  meta_title: z.string().nullable(),
  name: z.string(),
  parent_category_id: z.string().nullable(),
  slug: z.string(),
  sort_order: z.number().nullable(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
});

export const hkCategoriesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  meta_description: z.string().optional().nullable(),
  meta_title: z.string().optional().nullable(),
  name: z.string(),
  parent_category_id: z.string().optional().nullable(),
  slug: z.string(),
  sort_order: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const hkCategoriesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional().nullable(),
  is_active: z.boolean().optional().nullable(),
  meta_description: z.string().optional().nullable(),
  meta_title: z.string().optional().nullable(),
  name: z.string().optional(),
  parent_category_id: z.string().optional().nullable(),
  slug: z.string().optional(),
  sort_order: z.number().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const hkCategoriesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_categories_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_categories_parent_category_id_fkey"),
    columns: z.tuple([z.literal("parent_category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_categories_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkCouponsRowSchema = z.object({
  applicable_categories: z.array(z.string()).nullable(),
  applicable_products: z.array(z.string()).nullable(),
  code: z.string(),
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  discount_type: z.string(),
  discount_value: z.number(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  maximum_discount_amount: z.number().nullable(),
  minimum_order_amount: z.number().nullable(),
  name: z.string(),
  updated_at: z.string().nullable(),
  usage_limit: z.number().nullable(),
  usage_limit_per_user: z.number().nullable(),
  used_count: z.number().nullable(),
  valid_from: z.string().nullable(),
  valid_until: z.string().nullable(),
});

export const hkCouponsInsertSchema = z.object({
  applicable_categories: z.array(z.string()).optional().nullable(),
  applicable_products: z.array(z.string()).optional().nullable(),
  code: z.string(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  discount_type: z.string(),
  discount_value: z.number(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  maximum_discount_amount: z.number().optional().nullable(),
  minimum_order_amount: z.number().optional().nullable(),
  name: z.string(),
  updated_at: z.string().optional().nullable(),
  usage_limit: z.number().optional().nullable(),
  usage_limit_per_user: z.number().optional().nullable(),
  used_count: z.number().optional().nullable(),
  valid_from: z.string().optional().nullable(),
  valid_until: z.string().optional().nullable(),
});

export const hkCouponsUpdateSchema = z.object({
  applicable_categories: z.array(z.string()).optional().nullable(),
  applicable_products: z.array(z.string()).optional().nullable(),
  code: z.string().optional(),
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  discount_type: z.string().optional(),
  discount_value: z.number().optional(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  maximum_discount_amount: z.number().optional().nullable(),
  minimum_order_amount: z.number().optional().nullable(),
  name: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  usage_limit: z.number().optional().nullable(),
  usage_limit_per_user: z.number().optional().nullable(),
  used_count: z.number().optional().nullable(),
  valid_from: z.string().optional().nullable(),
  valid_until: z.string().optional().nullable(),
});

export const hkCouponsRelationshipsSchema = z.tuple([]);

export const hkOrderItemsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  option_details: orderItemOptionDetailsSchema.nullable(),
  order_id: z.string(),
  product_id: z.string(),
  product_name: z.string(),
  product_sku: z.string(),
  quantity: z.number(),
  total_price: z.number(),
  unit_price: z.number(),
  variant_id: z.string().nullable(),
  variant_sku: z.string().nullable(),
});

export const hkOrderItemsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  option_details: orderItemOptionDetailsSchema.optional().nullable(),
  order_id: z.string(),
  product_id: z.string(),
  product_name: z.string(),
  product_sku: z.string(),
  quantity: z.number(),
  total_price: z.number(),
  unit_price: z.number(),
  variant_id: z.string().optional().nullable(),
  variant_sku: z.string().optional().nullable(),
});

export const hkOrderItemsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  option_details: orderItemOptionDetailsSchema.optional().nullable(),
  order_id: z.string().optional(),
  product_id: z.string().optional(),
  product_name: z.string().optional(),
  product_sku: z.string().optional(),
  quantity: z.number().optional(),
  total_price: z.number().optional(),
  unit_price: z.number().optional(),
  variant_id: z.string().optional().nullable(),
  variant_sku: z.string().optional().nullable(),
});

export const hkOrderItemsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_order_items_order_id_fkey"),
    columns: z.tuple([z.literal("order_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_orders"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_order_items_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_order_items_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_order_items_variant_id_fkey"),
    columns: z.tuple([z.literal("variant_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_product_variants"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const orderStatusSchema = z.union([
  z.literal("pending"),
  z.literal("confirmed"),
  z.literal("processing"),
  z.literal("shipped"),
  z.literal("delivered"),
  z.literal("cancelled"),
  z.literal("refunded"),
]);

export const hkOrdersInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  customer_email: z.string(),
  customer_name: z.string(),
  customer_phone: z.string(),
  delivered_at: z.string().optional().nullable(),
  discount_amount: z.number().optional().nullable(),
  guest_email: z.string().optional().nullable(),
  id: z.string().optional(),
  order_notes: z.string().optional().nullable(),
  order_number: z.string(),
  shipped_at: z.string().optional().nullable(),
  shipping_address_line1: z.string(),
  shipping_address_line2: z.string().optional().nullable(),
  shipping_amount: z.number().optional().nullable(),
  shipping_city: z.string(),
  shipping_country: z.string().optional().nullable(),
  shipping_name: z.string(),
  shipping_notes: z.string().optional().nullable(),
  shipping_phone: z.string(),
  shipping_postal_code: z.string(),
  shipping_state: z.string(),
  status: orderStatusSchema.optional().nullable(),
  subtotal_amount: z.number(),
  tax_amount: z.number().optional().nullable(),
  total_amount: z.number(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkOrdersUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  customer_email: z.string().optional(),
  customer_name: z.string().optional(),
  customer_phone: z.string().optional(),
  delivered_at: z.string().optional().nullable(),
  discount_amount: z.number().optional().nullable(),
  guest_email: z.string().optional().nullable(),
  id: z.string().optional(),
  order_notes: z.string().optional().nullable(),
  order_number: z.string().optional(),
  shipped_at: z.string().optional().nullable(),
  shipping_address_line1: z.string().optional(),
  shipping_address_line2: z.string().optional().nullable(),
  shipping_amount: z.number().optional().nullable(),
  shipping_city: z.string().optional(),
  shipping_country: z.string().optional().nullable(),
  shipping_name: z.string().optional(),
  shipping_notes: z.string().optional().nullable(),
  shipping_phone: z.string().optional(),
  shipping_postal_code: z.string().optional(),
  shipping_state: z.string().optional(),
  status: orderStatusSchema.optional().nullable(),
  subtotal_amount: z.number().optional(),
  tax_amount: z.number().optional().nullable(),
  total_amount: z.number().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkOrdersRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_orders_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const paymentStatusSchema = z.union([
  z.literal("pending"),
  z.literal("processing"),
  z.literal("completed"),
  z.literal("failed"),
  z.literal("cancelled"),
  z.literal("refunded"),
]);

export const hkPaymentsInsertSchema = z.object({
  amount: z.number(),
  created_at: z.string().optional().nullable(),
  currency: z.string().optional().nullable(),
  failed_at: z.string().optional().nullable(),
  failure_reason: z.string().optional().nullable(),
  id: z.string().optional(),
  order_id: z.string(),
  payment_details: paymentDetailsSchema.optional().nullable(),
  payment_method: z.string(),
  payment_provider: z.string().optional().nullable(),
  processed_at: z.string().optional().nullable(),
  provider_payment_id: z.string().optional().nullable(),
  status: paymentStatusSchema.optional().nullable(),
});

export const hkPaymentsUpdateSchema = z.object({
  amount: z.number().optional(),
  created_at: z.string().optional().nullable(),
  currency: z.string().optional().nullable(),
  failed_at: z.string().optional().nullable(),
  failure_reason: z.string().optional().nullable(),
  id: z.string().optional(),
  order_id: z.string().optional(),
  payment_details: paymentDetailsSchema.optional().nullable(),
  payment_method: z.string().optional(),
  payment_provider: z.string().optional().nullable(),
  processed_at: z.string().optional().nullable(),
  provider_payment_id: z.string().optional().nullable(),
  status: paymentStatusSchema.optional().nullable(),
});

export const hkPaymentsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_payments_order_id_fkey"),
    columns: z.tuple([z.literal("order_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_orders"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductImagesRowSchema = z.object({
  alt_text: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  image_url: z.string(),
  is_primary: z.boolean().nullable(),
  product_id: z.string(),
  sort_order: z.number().nullable(),
});

export const hkProductImagesInsertSchema = z.object({
  alt_text: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string(),
  is_primary: z.boolean().optional().nullable(),
  product_id: z.string(),
  sort_order: z.number().optional().nullable(),
});

export const hkProductImagesUpdateSchema = z.object({
  alt_text: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  image_url: z.string().optional(),
  is_primary: z.boolean().optional().nullable(),
  product_id: z.string().optional(),
  sort_order: z.number().optional().nullable(),
});

export const hkProductImagesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_images_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_images_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductOptionGroupsRowSchema = z.object({
  created_at: z.string().nullable(),
  display_type: z.string().nullable(),
  id: z.string(),
  is_required: z.boolean().nullable(),
  name: z.string(),
  product_id: z.string(),
  sort_order: z.number().nullable(),
});

export const hkProductOptionGroupsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  display_type: z.string().optional().nullable(),
  id: z.string().optional(),
  is_required: z.boolean().optional().nullable(),
  name: z.string(),
  product_id: z.string(),
  sort_order: z.number().optional().nullable(),
});

export const hkProductOptionGroupsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  display_type: z.string().optional().nullable(),
  id: z.string().optional(),
  is_required: z.boolean().optional().nullable(),
  name: z.string().optional(),
  product_id: z.string().optional(),
  sort_order: z.number().optional().nullable(),
});

export const hkProductOptionGroupsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_option_groups_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_option_groups_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductOptionValuesRowSchema = z.object({
  additional_price: z.number().nullable(),
  color_code: z.string().nullable(),
  created_at: z.string().nullable(),
  display_name: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  option_group_id: z.string(),
  sort_order: z.number().nullable(),
  value: z.string(),
});

export const hkProductOptionValuesInsertSchema = z.object({
  additional_price: z.number().optional().nullable(),
  color_code: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  option_group_id: z.string(),
  sort_order: z.number().optional().nullable(),
  value: z.string(),
});

export const hkProductOptionValuesUpdateSchema = z.object({
  additional_price: z.number().optional().nullable(),
  color_code: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  display_name: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  option_group_id: z.string().optional(),
  sort_order: z.number().optional().nullable(),
  value: z.string().optional(),
});

export const hkProductOptionValuesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_option_values_option_group_id_fkey"),
    columns: z.tuple([z.literal("option_group_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_product_option_groups"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductReviewsRowSchema = z.object({
  approved_at: z.string().nullable(),
  approved_by: z.string().nullable(),
  content: z.string(),
  created_at: z.string().nullable(),
  helpful_count: z.number().nullable(),
  id: z.string(),
  image_urls: z.array(z.string()).nullable(),
  is_approved: z.boolean().nullable(),
  is_recommended: z.boolean().nullable(),
  not_helpful_count: z.number().nullable(),
  order_item_id: z.string().nullable(),
  product_id: z.string(),
  rating: z.number(),
  title: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const hkProductReviewsInsertSchema = z.object({
  approved_at: z.string().optional().nullable(),
  approved_by: z.string().optional().nullable(),
  content: z.string(),
  created_at: z.string().optional().nullable(),
  helpful_count: z.number().optional().nullable(),
  id: z.string().optional(),
  image_urls: z.array(z.string()).optional().nullable(),
  is_approved: z.boolean().optional().nullable(),
  is_recommended: z.boolean().optional().nullable(),
  not_helpful_count: z.number().optional().nullable(),
  order_item_id: z.string().optional().nullable(),
  product_id: z.string(),
  rating: z.number(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const hkProductReviewsUpdateSchema = z.object({
  approved_at: z.string().optional().nullable(),
  approved_by: z.string().optional().nullable(),
  content: z.string().optional(),
  created_at: z.string().optional().nullable(),
  helpful_count: z.number().optional().nullable(),
  id: z.string().optional(),
  image_urls: z.array(z.string()).optional().nullable(),
  is_approved: z.boolean().optional().nullable(),
  is_recommended: z.boolean().optional().nullable(),
  not_helpful_count: z.number().optional().nullable(),
  order_item_id: z.string().optional().nullable(),
  product_id: z.string().optional(),
  rating: z.number().optional(),
  title: z.string().optional().nullable(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const hkProductReviewsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_reviews_approved_by_fkey"),
    columns: z.tuple([z.literal("approved_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_reviews_order_item_id_fkey"),
    columns: z.tuple([z.literal("order_item_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_order_items"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_reviews_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_reviews_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_reviews_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductVariantsRowSchema = z.object({
  additional_price: z.number().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  low_stock_threshold: z.number().nullable(),
  option_combinations: productOptionCombinationsSchema,
  product_id: z.string(),
  reserved_quantity: z.number().nullable(),
  stock_quantity: z.number(),
  updated_at: z.string().nullable(),
  variant_sku: z.string(),
  weight: z.number().nullable(),
});

export const hkProductVariantsInsertSchema = z.object({
  additional_price: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  low_stock_threshold: z.number().optional().nullable(),
  option_combinations: productOptionCombinationsSchema,
  product_id: z.string(),
  reserved_quantity: z.number().optional().nullable(),
  stock_quantity: z.number().optional(),
  updated_at: z.string().optional().nullable(),
  variant_sku: z.string(),
  weight: z.number().optional().nullable(),
});

export const hkProductVariantsUpdateSchema = z.object({
  additional_price: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  low_stock_threshold: z.number().optional().nullable(),
  option_combinations: productOptionCombinationsSchema.optional(),
  product_id: z.string().optional(),
  reserved_quantity: z.number().optional().nullable(),
  stock_quantity: z.number().optional(),
  updated_at: z.string().optional().nullable(),
  variant_sku: z.string().optional(),
  weight: z.number().optional().nullable(),
});

export const hkProductVariantsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_variants_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_variants_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductViewsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  ip_address: z.unknown(),
  product_id: z.string(),
  referrer_url: z.string().nullable(),
  session_id: z.string().nullable(),
  user_agent: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const hkProductViewsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ip_address: z.unknown().optional(),
  product_id: z.string(),
  referrer_url: z.string().optional().nullable(),
  session_id: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkProductViewsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  ip_address: z.unknown().optional(),
  product_id: z.string().optional(),
  referrer_url: z.string().optional().nullable(),
  session_id: z.string().optional().nullable(),
  user_agent: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkProductViewsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_product_views_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_views_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_product_views_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkProductsRowSchema = z.object({
  base_price: z.number(),
  brand_id: z.string().nullable(),
  care_instructions: z.string().nullable(),
  category_id: z.string(),
  cost_price: z.number().nullable(),
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  dimensions: productDimensionsSchema.nullable(),
  id: z.string(),
  is_active: z.boolean().nullable(),
  is_bestseller: z.boolean().nullable(),
  is_featured: z.boolean().nullable(),
  is_new: z.boolean().nullable(),
  long_description: z.string().nullable(),
  materials: z.array(z.string()).nullable(),
  meta_description: z.string().nullable(),
  meta_title: z.string().nullable(),
  name: z.string(),
  sale_price: z.number().nullable(),
  search_keywords: z.array(z.string()).nullable(),
  short_description: z.string().nullable(),
  sku: z.string(),
  slug: z.string(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
  warranty_period: z.number().nullable(),
  weight: z.number().nullable(),
});

export const hkProductsInsertSchema = z.object({
  base_price: z.number(),
  brand_id: z.string().optional().nullable(),
  care_instructions: z.string().optional().nullable(),
  category_id: z.string(),
  cost_price: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  dimensions: productDimensionsSchema.optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  is_bestseller: z.boolean().optional().nullable(),
  is_featured: z.boolean().optional().nullable(),
  is_new: z.boolean().optional().nullable(),
  long_description: z.string().optional().nullable(),
  materials: z.array(z.string()).optional().nullable(),
  meta_description: z.string().optional().nullable(),
  meta_title: z.string().optional().nullable(),
  name: z.string(),
  sale_price: z.number().optional().nullable(),
  search_keywords: z.array(z.string()).optional().nullable(),
  short_description: z.string().optional().nullable(),
  sku: z.string(),
  slug: z.string(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  warranty_period: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
});

export const hkProductsUpdateSchema = z.object({
  base_price: z.number().optional(),
  brand_id: z.string().optional().nullable(),
  care_instructions: z.string().optional().nullable(),
  category_id: z.string().optional(),
  cost_price: z.number().optional().nullable(),
  created_at: z.string().optional().nullable(),
  created_by: z.string().optional().nullable(),
  dimensions: productDimensionsSchema.optional().nullable(),
  id: z.string().optional(),
  is_active: z.boolean().optional().nullable(),
  is_bestseller: z.boolean().optional().nullable(),
  is_featured: z.boolean().optional().nullable(),
  is_new: z.boolean().optional().nullable(),
  long_description: z.string().optional().nullable(),
  materials: z.array(z.string()).optional().nullable(),
  meta_description: z.string().optional().nullable(),
  meta_title: z.string().optional().nullable(),
  name: z.string().optional(),
  sale_price: z.number().optional().nullable(),
  search_keywords: z.array(z.string()).optional().nullable(),
  short_description: z.string().optional().nullable(),
  sku: z.string().optional(),
  slug: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
  warranty_period: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
});

export const hkProductsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_products_brand_id_fkey"),
    columns: z.tuple([z.literal("brand_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_brands"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkReviewVotesRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  is_helpful: z.boolean(),
  review_id: z.string(),
  user_id: z.string(),
});

export const hkReviewVotesInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_helpful: z.boolean(),
  review_id: z.string(),
  user_id: z.string(),
});

export const hkReviewVotesUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_helpful: z.boolean().optional(),
  review_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const hkReviewVotesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_review_votes_review_id_fkey"),
    columns: z.tuple([z.literal("review_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_product_reviews"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_review_votes_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkSearchLogsRowSchema = z.object({
  clicked_product_id: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  results_count: z.number().nullable(),
  search_filters: searchFiltersSchema.nullable(),
  search_query: z.string(),
  session_id: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const hkSearchLogsInsertSchema = z.object({
  clicked_product_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  results_count: z.number().optional().nullable(),
  search_filters: searchFiltersSchema.optional().nullable(),
  search_query: z.string(),
  session_id: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkSearchLogsUpdateSchema = z.object({
  clicked_product_id: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  results_count: z.number().optional().nullable(),
  search_filters: searchFiltersSchema.optional().nullable(),
  search_query: z.string().optional(),
  session_id: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const hkSearchLogsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_search_logs_clicked_product_id_fkey"),
    columns: z.tuple([z.literal("clicked_product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_search_logs_clicked_product_id_fkey"),
    columns: z.tuple([z.literal("clicked_product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_search_logs_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkSystemSettingsRowSchema = z.object({
  created_at: z.string().nullable(),
  description: z.string().nullable(),
  id: z.string(),
  is_public: z.boolean().nullable(),
  setting_key: z.string(),
  setting_type: z.string().nullable(),
  setting_value: z.string(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
});

export const hkSystemSettingsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  setting_key: z.string(),
  setting_type: z.string().optional().nullable(),
  setting_value: z.string(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const hkSystemSettingsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  id: z.string().optional(),
  is_public: z.boolean().optional().nullable(),
  setting_key: z.string().optional(),
  setting_type: z.string().optional().nullable(),
  setting_value: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  updated_by: z.string().optional().nullable(),
});

export const hkSystemSettingsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_system_settings_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkUserAddressesRowSchema = z.object({
  address_line1: z.string(),
  address_line2: z.string().nullable(),
  address_name: z.string().nullable(),
  city: z.string(),
  country: z.string().nullable(),
  created_at: z.string().nullable(),
  id: z.string(),
  is_default: z.boolean().nullable(),
  postal_code: z.string(),
  recipient_name: z.string(),
  recipient_phone: z.string(),
  state: z.string(),
  updated_at: z.string().nullable(),
  user_id: z.string(),
});

export const hkUserAddressesInsertSchema = z.object({
  address_line1: z.string(),
  address_line2: z.string().optional().nullable(),
  address_name: z.string().optional().nullable(),
  city: z.string(),
  country: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_default: z.boolean().optional().nullable(),
  postal_code: z.string(),
  recipient_name: z.string(),
  recipient_phone: z.string(),
  state: z.string(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const hkUserAddressesUpdateSchema = z.object({
  address_line1: z.string().optional(),
  address_line2: z.string().optional().nullable(),
  address_name: z.string().optional().nullable(),
  city: z.string().optional(),
  country: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  is_default: z.boolean().optional().nullable(),
  postal_code: z.string().optional(),
  recipient_name: z.string().optional(),
  recipient_phone: z.string().optional(),
  state: z.string().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const hkUserAddressesRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_user_addresses_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkUserCouponUsageRowSchema = z.object({
  coupon_id: z.string(),
  discount_amount: z.number(),
  id: z.string(),
  order_id: z.string(),
  used_at: z.string().nullable(),
  user_id: z.string(),
});

export const hkUserCouponUsageInsertSchema = z.object({
  coupon_id: z.string(),
  discount_amount: z.number(),
  id: z.string().optional(),
  order_id: z.string(),
  used_at: z.string().optional().nullable(),
  user_id: z.string(),
});

export const hkUserCouponUsageUpdateSchema = z.object({
  coupon_id: z.string().optional(),
  discount_amount: z.number().optional(),
  id: z.string().optional(),
  order_id: z.string().optional(),
  used_at: z.string().optional().nullable(),
  user_id: z.string().optional(),
});

export const hkUserCouponUsageRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_user_coupon_usage_coupon_id_fkey"),
    columns: z.tuple([z.literal("coupon_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_coupons"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_user_coupon_usage_order_id_fkey"),
    columns: z.tuple([z.literal("order_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_orders"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_user_coupon_usage_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const hkUsersRowSchema = z.object({
  birth_date: z.string().nullable(),
  created_at: z.string().nullable(),
  first_name: z.string().nullable(),
  gender: z.string().nullable(),
  id: z.string(),
  last_login_at: z.string().nullable(),
  last_name: z.string().nullable(),
  marketing_consent: z.boolean().nullable(),
  phone: z.string().nullable(),
  profile_image_url: z.string().nullable(),
  sms_consent: z.boolean().nullable(),
  updated_at: z.string().nullable(),
});

export const hkUsersInsertSchema = z.object({
  birth_date: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string(),
  last_login_at: z.string().optional().nullable(),
  last_name: z.string().optional().nullable(),
  marketing_consent: z.boolean().optional().nullable(),
  phone: z.string().optional().nullable(),
  profile_image_url: z.string().optional().nullable(),
  sms_consent: z.boolean().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const hkUsersUpdateSchema = z.object({
  birth_date: z.string().optional().nullable(),
  created_at: z.string().optional().nullable(),
  first_name: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  id: z.string().optional(),
  last_login_at: z.string().optional().nullable(),
  last_name: z.string().optional().nullable(),
  marketing_consent: z.boolean().optional().nullable(),
  phone: z.string().optional().nullable(),
  profile_image_url: z.string().optional().nullable(),
  sms_consent: z.boolean().optional().nullable(),
  updated_at: z.string().optional().nullable(),
});

export const hkUsersRelationshipsSchema = z.tuple([]);

export const hkWishlistsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string(),
  product_id: z.string(),
  user_id: z.string(),
});

export const hkWishlistsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  product_id: z.string(),
  user_id: z.string(),
});

export const hkWishlistsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional(),
  product_id: z.string().optional(),
  user_id: z.string().optional(),
});

export const hkWishlistsRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_wishlists_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_products"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_wishlists_product_id_fkey"),
    columns: z.tuple([z.literal("product_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("vw_hk_products_summary"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_wishlists_user_id_fkey"),
    columns: z.tuple([z.literal("user_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const vwHkOrderStatisticsRowSchema = z.object({
  avg_order_value: z.number().nullable(),
  delivered_orders: z.number().nullable(),
  order_count: z.number().nullable(),
  order_date: z.string().nullable(),
  total_revenue: z.number().nullable(),
});

export const vwHkOrderStatisticsRelationshipsSchema = z.tuple([]);

export const vwHkProductsSummaryRowSchema = z.object({
  avg_rating: z.number().nullable(),
  base_price: z.number().nullable(),
  brand_id: z.string().nullable(),
  brand_name: z.string().nullable(),
  care_instructions: z.string().nullable(),
  category_id: z.string().nullable(),
  category_name: z.string().nullable(),
  category_slug: z.string().nullable(),
  cost_price: z.number().nullable(),
  created_at: z.string().nullable(),
  created_by: z.string().nullable(),
  dimensions: productDimensionsSchema.nullable(),
  id: z.string().nullable(),
  is_active: z.boolean().nullable(),
  is_bestseller: z.boolean().nullable(),
  is_featured: z.boolean().nullable(),
  is_new: z.boolean().nullable(),
  long_description: z.string().nullable(),
  materials: z.array(z.string()).nullable(),
  meta_description: z.string().nullable(),
  meta_title: z.string().nullable(),
  name: z.string().nullable(),
  primary_image_url: z.string().nullable(),
  review_count: z.number().nullable(),
  sale_price: z.number().nullable(),
  search_keywords: z.array(z.string()).nullable(),
  short_description: z.string().nullable(),
  sku: z.string().nullable(),
  slug: z.string().nullable(),
  total_stock: z.number().nullable(),
  updated_at: z.string().nullable(),
  updated_by: z.string().nullable(),
  variant_count: z.number().nullable(),
  warranty_period: z.number().nullable(),
  weight: z.number().nullable(),
});

export const vwHkProductsSummaryRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("hk_products_brand_id_fkey"),
    columns: z.tuple([z.literal("brand_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_brands"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_category_id_fkey"),
    columns: z.tuple([z.literal("category_id")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_categories"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_created_by_fkey"),
    columns: z.tuple([z.literal("created_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
  z.object({
    foreignKeyName: z.literal("hk_products_updated_by_fkey"),
    columns: z.tuple([z.literal("updated_by")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("hk_admin_users"),
    referencedColumns: z.tuple([z.literal("id")]),
  }),
]);

export const vwHkUserSocialAccountsRowSchema = z.object({
  created_at: z.string().nullable(),
  id: z.string().nullable(),
  provider: z.string().nullable(),
  provider_email: z.string().nullable(),
  provider_name: z.string().nullable(),
  provider_picture: z.string().nullable(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const vwHkUserSocialAccountsInsertSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  provider: z.never().optional(),
  provider_email: z.never().optional(),
  provider_name: z.never().optional(),
  provider_picture: z.never().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const vwHkUserSocialAccountsUpdateSchema = z.object({
  created_at: z.string().optional().nullable(),
  id: z.string().optional().nullable(),
  provider: z.never().optional(),
  provider_email: z.never().optional(),
  provider_name: z.never().optional(),
  provider_picture: z.never().optional(),
  updated_at: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
});

export const vwHkUserSocialAccountsRelationshipsSchema = z.tuple([]);

export const hkOrdersRowSchema = z.object({
  created_at: z.string().nullable(),
  customer_email: z.string(),
  customer_name: z.string(),
  customer_phone: z.string(),
  delivered_at: z.string().nullable(),
  discount_amount: z.number().nullable(),
  guest_email: z.string().nullable(),
  id: z.string(),
  order_notes: z.string().nullable(),
  order_number: z.string(),
  shipped_at: z.string().nullable(),
  shipping_address_line1: z.string(),
  shipping_address_line2: z.string().nullable(),
  shipping_amount: z.number().nullable(),
  shipping_city: z.string(),
  shipping_country: z.string().nullable(),
  shipping_name: z.string(),
  shipping_notes: z.string().nullable(),
  shipping_phone: z.string(),
  shipping_postal_code: z.string(),
  shipping_state: z.string(),
  status: orderStatusSchema.nullable(),
  subtotal_amount: z.number(),
  tax_amount: z.number().nullable(),
  total_amount: z.number(),
  updated_at: z.string().nullable(),
  user_id: z.string().nullable(),
});

export const hkPaymentsRowSchema = z.object({
  amount: z.number(),
  created_at: z.string().nullable(),
  currency: z.string().nullable(),
  failed_at: z.string().nullable(),
  failure_reason: z.string().nullable(),
  id: z.string(),
  order_id: z.string(),
  payment_details: paymentDetailsSchema.nullable(),
  payment_method: z.string(),
  payment_provider: z.string().nullable(),
  processed_at: z.string().nullable(),
  provider_payment_id: z.string().nullable(),
  status: paymentStatusSchema.nullable(),
});
